project:
  type: website
  output-dir: docs

website:
  site-url: https://www.joshgregory42.github.io
  # title: 'Josh Gregory'
  navbar:
    title: "Josh Gregory" # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    # collapse-level: 1
    left: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home # use 'text' option to update the name as you want it to appear in your navbar
      - href: about.qmd
        text: About
      - projects/index.qmd  
      - posts.qmd
      - href: resume_jag.pdf
        text: Resume
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-a-gregory
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/joshgregory42
      - icon: twitter
        href: https://twitter.com/josh_a_gregory
      # - icon: rss
      #   href: index.html

  page-footer:
    background: light # or dark
    # left:
    #   - "Copyright 2024, Josh Gregory"
    right:
      - icon: github
        href: https://github.com/joshgregory42/joshgregory42.github.io
      # - icon: twitter
        # href: https://twitter.com/josh_a_gregory

format:
  html:
    theme: 
      dark: [darkly, styles-dark.scss]
      light: [litera, styles.scss]
    mermaid:
      light: default
      dark: dark
    highlight-style: a11y-dark
    # mainfont: 'SF Pro'
    toc: true
    code-copy: true
    code-overflow: wrap
    page-layout: full

editor: visual