project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Josh Gregory" # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    left: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home # use 'text' option to update the name as you want it to appear in your navbar
      - href: about.qmd
        text: About
      - posts.qmd
      - href: resume_jag.pdf
        text: Resume
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-a-gregory
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/joshgregory42
      - icon: twitter
        href: https://twitter.com/josh_a_gregory

  page-footer:
    background: light # or dark
    # left:
<<<<<<< HEAD
      # - "Copyright 2024, Josh Gregory"
=======
    #   - "Copyright 2024, Josh Gregory"
>>>>>>> dev
    right:
      - icon: github
        href: https://github.com/joshgregory42
      # - icon: twitter
        # href: https://twitter.com/josh_a_gregory

format:
  html:
    theme: 
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: 'SF Pro'
    toc: true
    code-copy: true
    code-overflow: wrap
    page-layout: full

editor: visual