---
title: "On Nuance and Humility"
author:
  - name: Josh Gregory
    url: https://joshgregory42.github.io/
    orcid: 0000-0002-4368-1171
    affiliation: College of Engineering & Applied Science, University of Colorado Boulder
    affiliation-url: https://www.colorado.edu/mechanical/ 
date: today
categories: [Writings, Thoughts] # self-defined categories
citation: 
  url: https://joshgregory42.github.io/posts/2024-08-09-nuance-humility/ 
draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

Throughout my time in university, and now graduate school, I have noticed the importance of both nuance as well as humility. These might seem like two separate subejcts, but together they allow for someone to keep their minds open while at the same time ensuring that they are keeping their minds open to *exactly* what someone else is being told. Which is typically **not** what one might hear the first time.

# The importance of nuance

When I was a freshman at Oregon State University in the fall of 2019, many of us on the floor would get together and talk. Eventually those conversations led into politics. OSU is pretty liberal, however there was one guy specifically that was pretty right-leaning. He later told me that I was the only person that he could talk politics with. That surprised me, and when I asked him why, he told me "because I know that we can have a conversation, you'll listen, and I won't come out of it angry". 

I tend to lean center-left on most topics, but something that my parents always made sure to instill was the importance of talking to people I disagree with. It shocked me that I was one of the only people that friend felt like he could have an actual conversation with. Sure, we disagreed about most things, but what I came away with was that for many of the big issues, we agreed. And I think that's a really key point here. Ever since then, I've seen the media show more and more (from both sides) that whoever the "out" or "crazy" group is (liberals is you're watching Fox, conservatives if you're watching CNN) is destroying the country. Not only that, but **all** of them are. Every single one. I think this is happening for one main reason.

## Generalizations are easy, nuance is hard

Maybe it's not that complicated. It's so freaking easy to say that all people who are conservative are hillbillies, live in the South, and are racist, homophobic idiots who contribute little to the U.S. economy. To disprove that, let's just look at one industry: aerospace. Two major universities in the South, Georgia Tech and the University of Alabama Huntsville, which are world-class in rocket propulsion. End of story. But it's not easy to discuss that nuance. It's *so* much easier to think that everyone in the South is lazy. 

> Another dimension of nuance here: the University of Alabama Huntsville's rocketry program was first founded by Wernher von Braun, a Nazi who came over to the United States during Operation Paperclip to help the United States win the Cold War (a great book on the topic is by Annie Jacobsen and is fittingly titled [Operation Paperclip](https://anniejacobsen.com/operation-paperclip/)).

I think that's the challenge that we all have in this day and age. It's much more profitable for social media companies to make you angry than to encourage nuanced discourse (when was the last time you saw a fight on Twitter that featured someone saying "Oh I see your perspective now, I was wrong"?). But that's the challenge, and I believe it is a doable one. We just need to practice.

# Nuance in science

This is one of the areas that is close to me, mostly because I'm in STEM. And it's a double-edged sword; I have read multiple papers that require nuance to decipher properly (both to find the subtleties in someone's great work or to prove that someone else is full of shit and hiding it really well), but have also found that **many** scientists lack the kind of nuance that I believe is required to be not only an excellent scientist and researcher, but also a communicator of what we do, how we do it, and its importance to society as a whole.

> What I'm going to say next is going to make many people in academia upset. After reading the next few paragraphs, you're probably going to think that I misheard or misunderstood what other people said. Maybe I did, who knows. But I also know what I heard, and know how it made me feel. 

## My conference experience

Over the past few weeks, I have attended my first few conferences as a graduate/Master's student. One specific experience stood out to me that I believe highlights the issues with arrogance and a lack of nuance within the scientific community.

One of the sessions of a conference I attended featured the conference organizer splitting up the audience into several groups. After the split, he told us that the goal was to have combinations of senior researchers (i.e. faculty, lab heads, etc.) and junior people (new graduate students, first and second-year PhD students, etc.) in one group so that the junior people can learn from the senior ones, but also just as important, the senior researchers gleaning some insight into what the junior researchers may be experiencing.

> That idealism is good and more of it should exist. But what followed next made me so angry I nearly got up and left.

One of the first things that I heard from some of the senior researchers what that interdisciplinary science does not get funded. Initially, I thought that I misheard him, but the other researchers in the group echoed similar sentiments, and an anti-interdisciplinary attitude soon followed. Not only that, I was taken aback by the sheer *certainty* of these researchers that interdisciplinary science is unfundable. I should preface my rebuttal with the fact that it is true that perhaps their specific interdisciplinary research has not received funding. They didn't mention the kind of research that wasn't receiving funding. With that in mind, it is worth noting that this was a mechanobiology conference. Most of these researchers have probably used nuclear magnetic resonance (NMR) or magnetic resonance imaging (MRI) in some form or another during their research.

It is widely known that the MRI machine is perhaps the most important machine that the medical profession has to diagnose a patient without cutting them open. Neil deGrasse Tyson explained this history in a bit more detail in an [interview](https://www.youtube.com/watch?v=pqQrL1K0Z5g) with Marques Brownlee. Expanding on this history a bit more, one of Neil deGrasse Tyson's professors was Ed Purcell, who won the [Nobel Prize in Physics 1952](https://www.nobelprize.org/prizes/physics/1952/summary/) along with Felix Bloch for developing nuclear magnetic resonance.

It wouldn't be until 1971 when Raymond Damadian published a [paper](https://doi.org/10.1126/science.171.3976.1151) titled *Tumor Detection by Nuclear Magnetic Resonance*, which is widely credited as the first paper on and the invention of the modern MRI machine.

My point in illustrating this story is that the fundamental technology driving one of the best medical devices in human history was discovered by an astrophysicist that had no interest in medicine. I find a deep irony in many individuals who have benefited from the breakthrough that is the MRI machine lambasting the "fact" that interdisciplinary science is unfundable.

There was another portion of this same small group discussion where the senior members were asked to turn to the younger members and ask for their perspective. This quite simply did not happen. The senior members were just talking to themselves. This made me extremely irritated. How can the same people who claim to be scientists and represent the field to the general public not show the minimum amount of open mindedness necessary to turn to others that are junior to them and solicit feedback? It reminded me of the cliques from high school, and not in a good way. I shouldn't be reminded of an episode of *Mean Girls* from those who claim to represent free scientific thinking at the highest level.

Then there was the pure social ineptitude of many of these senior researchers. One of which, when asked to share his thoughts, told the entire room "I guess everyone thinks I'm awesome". This garnered a laugh from everyone, who thought he was joking. He then stared blankly at the moderator and revealed that he had nothing to add to the conversation.

This leads me to my next major point:

## A PhD does not make you a god. Stop acting like it.

Social ineptitude leads into this. This same conference led me to meet another researcher who told me that the economy was going to crash. When I told him that it was difficult to know that, he said that he knows for certain and had been "paying attention to the Fed's rates". These two interactions highlight the sheer arrogance that I found many researchers to have.

In my opinion, a certain amount of arrogance is acceptable when you've achieved something incredible. Steph Curry being a bit arrogant after winning the gold at the recent Olympics? To me, that's okay. Lewis Hamilton celebrating after winning his seventh world title? Also okay.

In STEM, however, I have noticed that many researchers who (as far as I can tell) have an oversized ego relative to their impact on the world. Most, if not all, of these researchers needed multiple minutes to explain the significance to their work. In my mind, that means your work is insignificant. If you can't explain the importance of your work in two sentences, it's not important.

I should contrast this with one of my mentors, who invented the pediatric pulse-oximiter. It's the medical device that doctors and nurses put on your finger during appointments. He invented the pediatric one that's used in practically every single NICU and delivery room in the world. Again, in my opinion, he has every right to be a little arrogant. He never was. Ever. He remains one of the most humble and kindest people I had the privilege and honor to learn from. I don't doubt for a second that his humility was a key driving force in his ability to literally save countless lives.


# How we can be better

The public's perception of scientists and science communication has no doubt been dampened by some of what I have discussed here. Even as someone *in science* I found my joy of it slightly diminished after the conference I discussed earlier. But the important thing here is that we can change. We must change. As the world grapples with more significant issues that impact more people, the importance of scientific communication similarly increases.

We must lead with humility and the same sense of discovery that every single great scientist posesses. It is our responsibility not to show off how smart we are, but instead to take people on a journey of discovery with us to come to the same incredible realizations about the world that we have. The world is a beautiful place, and science is the best tool us humans have to understand it. We must take as many people along on this ride with us, both to ensure that the public is scientifically literate, but also to ensure that the generations to follow are open-minded, kind, and have the social skills to make the world a better place. Not just for their fellow academics or researchers, but for everyone.


> You have enemies? Why, it is the story of every man who has done a great deed or created a new idea. It is the cloud which thunders around everything that shines. Fame must have enemies, as light must have gnats. Do not bother yourself about it; disdain. Keep your mind serene as you keep your life clear.
> 
> — Victor Hugo, Villemain, 1845
