---
title: "Research Excellence Award Statement"
description: "Reflections on my research"
author:
  - name: Josh Gregory
    url: https://joshgregory42.github.io/
    orcid: 0000-0002-4368-1171
    affiliation: College of Engineering & Applied Science, University of Colorado Boulder
    affiliation-url: https://www.colorado.edu/mechanical/ 
date: 05-05-2024
categories: [Research, College] # self-defined categories
citation: 
  url: https://joshgregory42.github.io/posts/2024-05-05-research-award/ 
draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---
> Every year, CU Boulder's College of Engineering & Applied Science hands out [awards](https://www.colorado.edu/engineering/academics/graduation/graduating-student-awards) to certain graduating students. Faculty and students from the engineering deparments within the College (i.e. mechanical, aerospace, civil, etc.) nominates students, who then submit statements for their individual award. Some of them are then selected by the College as a whole. One of them is the Research Excellence Award, which I was fortunate enough to receive from the College after being nominated by a few faculty members. As part of the selection process, each nominee had to write a statement about research and any advice they would give to other students. What follows is my statement.



Research lets me act like a curious five-year-old. An unwavering sense of wonder and curiosity about the world is what led me to conducting research in various fields for each year of my undergraduate career. During my time at CU, I have contributed to research at the intersection of biology and mechanical engineering under [Dr. Debanjan Mukherjee](https://www.flowphysicslab.com/), worked with the National Renewable Energy Laboratory ([NREL](https://www.nrel.gov/)) on fundamental research in heat transfer and thermodynamics, and more recently began my Master's thesis on the topic of artificial neural networks applied to brain vasculature to better predict and understand strokes. The commonality between all of these projects is an understanding and application of fundamentals across varying fields, a perspective that is helpful in both uniting different fields and forging new paths at their intersections.


My work with Dr. Mukherjee is currently investigating the mechanical properties of blood clots in a dynamic and transient sense. That is, using *in vitro* experiments to inform *in silico* models of blood clots. The novel fusion of these two typically disparate approaches allows us to extract the boundaries of blood clots as they develop over time, allowing for significantly more accurate computational modeling of blood clot dynamics. My contribution has been on the image processing side, assisting PhD student Chayut Teeraratkul in determining the techniques to extract the blood clot boundaries. My work enabled the group to obtain correct image processing parameters for a wide range of experiments, allowing for our code to be applied to more datasets. This work is currently being written for publication and is going to be published in the following months, with the code set for an open-source release to the community. It is inherently transdisciplinary, utilizing knowlege from mechanical engineering, biology, and computer science. This has allowed me to gain familiarity with diverse areas such as blood clot hemodynamics, image processing, and software development. Recognizing the importance of this work, CU awarded it a [UROP](https://www.colorado.edu/urop/) grant in the summer of 2023.


Also during the summer of 2023, I interned at NREL, working on additively manufacturing heat exchangers for use in energy storage. Sometimes called a "thermal battery", these materials utilize microscopic phase-change materials to store energy in the form of heat, in contrast to the status quo that is a chemical reaction. This work required knowledge of heat transfer, materials science, thermodynamics, and fluid mechanics, but also allowed me to work with scientists in other fields, such as chemistry. Throughout the summer, I was able to determine the optimal 3D printing settings for these heat exchangers and also gained experience in thermodynamic characterization, utilizing machines such as differential scanning calorimeters. This work has the potential to contribute significantly to energy storage issues of our time. Current lithium-ion batteries are not adequate for large scale storage of energy, such as that generated by solar panels. Furthermore, it allows the insulation of houses to store incoming sunlight, drastically reducing the cost of the monthly utility bill. Due to its manufacturing process, it also allows for cheaper cooling and heating solutions for lower-income communities in a world beset by climate change. My work was presented in a poster session within NREL and is currently in manuscript form to be published soon.

More recently, I have begun work on my Master's Thesis, which focuses on one of the most crucial tasks in Dr. Mukherjee's lab: automated segmentation of the M2, P2, and A2 vessels of the brain, which are increasingly found to be the locations of stroke. As such, understanding the fluid mechanics of these vessels is vital to predicting stroke risk. The goal of my thesis is to take CT images from clinicians and feed them to a neural network to extract these vessels, allowing for significantly better stroke risk assessment in the research and clinical settings. This is also a collaboration between our lab and others, namely Drs. Timothy Stalker and Maruzio Pacifici from Thomas Jefferson University, Dr. Vincent Tutino from the University of Buffalo, and other collaborators from UMC Amsterdam and CU Anschutz. This is a collaboration across fields as well as researchers, requiring knowledge not only of the mechanical engineering for which I am familiar, but also computer science, image processing, and biology.


My best advice to a future student is to embrace curiosity and approach challenges with the mindset of a five-year-old. Be curious, insatiably so. Research allows you to work on problems you never thought possible with people in incredible fields. It allows you to learn how to think through problems with others, collaborating to uncover or create something new in this world. On the other hand, resist the temptation to become overly specialized. Put yourself in a position to learn new things. Ignorance can be helpful when utilized in the correct way. The fundamentals of engineering are just that; the fundamentals. How you apply them is up to you. My career trajectory initially pointed towards the aerospace industry. As a freshman, I ran computational fluid dynamics simulations of rocket engines, eventually progressing to the simulation lead for various rocket teams. However, the pandemic sparked a desire to contribute to the medical field. Recognizing the shared fundamentals of fluid mechanics between rocket engines and the cardiovascular system, I pivoted, embracing my curiosity and desire to help others, despite my ignorance in the field.

Two other lessons that I found useful in both research and life: question assumptions and find the nuance. Assumptions in research are often the most challenging part of a project, so gaining experience in making them helps you become better in your field as well as in life. Finding nuance is also key. In today's world it is easy to make blanket statements and assume that either you know everything, or the person you are working for does. Research has a way of humbling everyone, no matter their stature. Not only will you learn to find nuance in your own ideas, but finding nuance in the ideas of others leads to new avenues of exploration in ways no one anticipates. This non-linear path is truly one of the most rewarding areas of research. Yes, it is littered with disappointing days, failed experiments, and false hopes. But it is also marked by success, new ideas, perseverance, and a curiosity to better understand the world around us.


Participation in research is participation in the scientific process. The same scientific process that Isaac Newton, Galileo Galilei, Madame Curie, and Jennifer Doudna all were a part of. It is a uniquely human experience that ties you to a lineage of people who create discoveries and technologies that cause the world to fundamentally change. Act like a five-year-old and celebrate your ignorance. Not knowing how difficult something is might be the very reason you end up doing it and changing the world.
